{{- $name := include "krab-precheck.name" . -}}
apiVersion: v1
kind: ServiceAccount
metadata: {name: {{ $name }}-dispatcher}
---
apiVersion: v1
kind: ServiceAccount
metadata: {name: {{ $name }}-collector}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata: {name: {{ $name }}-dispatcher}
rules:
  - apiGroups: [""]
    resources: [nodes]
    verbs: [get, list, patch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata: {name: {{ $name }}-dispatcher}
roleRef: {apiGroup: rbac.authorization.k8s.io, kind: ClusterRole, name: {{ $name }}-dispatcher}
subjects:
  - {kind: ServiceAccount, name: {{ $name }}-dispatcher, namespace: {{ .Release.Namespace }}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: {name: {{ $name }}-dispatcher}
rules:
  - apiGroups: [batch]
    resources: [jobs]
    verbs: [create, get, list, delete]
  - apiGroups: [""]
    resources: [pods]
    verbs: [list]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: {name: {{ $name }}-dispatcher}
roleRef: {apiGroup: rbac.authorization.k8s.io, kind: Role, name: {{ $name }}-dispatcher}
subjects:
  - {kind: ServiceAccount, name: {{ $name }}-dispatcher, namespace: {{ .Release.Namespace }}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata: {name: {{ $name }}-collector}
rules:
  - apiGroups: [""]
    resources: [nodes]
    verbs: [list]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata: {name: {{ $name }}-collector}
roleRef: {apiGroup: rbac.authorization.k8s.io, kind: ClusterRole, name: {{ $name }}-collector}
subjects:
  - {kind: ServiceAccount, name: {{ $name }}-collector, namespace: {{ .Release.Namespace }}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: {name: {{ $name }}-collector}
rules:
  - apiGroups: [batch]
    resources: [jobs]
    verbs: [get, list]
  - apiGroups: [""]
    resources: [pods, pods/log]
    verbs: [get, list]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: {name: {{ $name }}-collector}
roleRef: {apiGroup: rbac.authorization.k8s.io, kind: Role, name: {{ $name }}-collector}
subjects:
  - {kind: ServiceAccount, name: {{ $name }}-collector, namespace: {{ .Release.Namespace }}}
